logging:
  level:
    #root: DEBUG
    org.springframework: INFO
#    com.example.sahil.practice.scope.connection: INFO

management:
  endpoints:
   beans:
      enabled: false
   web:
      exposure:
        include: "*"