logging:
  level:
    #root: DEBUG
    org.springframework: INFO
    com.example.sahil.practice.aop: INFO

management:
  endpoints:
   beans:
      enabled: false
   web:
      exposure:
        include: "*"